### ISSUE TITLE
Does this differ functionally from fuse-umfuse-fat?

### ISSUE THREAD

**Issue by nabijaczleweli** [virtualsquare/fusefatfs#3]
Beside fuse-umfuse-fat building `fusefat` and this building `fusefatfs`, of course.

A cursory comparison of mounting an image reveals no behavioural differences. I'd like to ship a live fusefat implementation over a dead-for-a-decade one if they're equivalent.

Also, are you expecting to tag `0.2`?

**Comment by rd235** [comment]
fusefatfs has been developed as a replacement for fusefat.

fusefatfs is based on the FAT file system module for embedded systems named [fatfs](http://elm-chan.org/fsw/ff/00index_e.html) by ChaN.
fatfs is widely used, so fusefatfs should be more reliable and should require less maintenance effort

**Comment by nabijaczleweli** [comment]
Sounds like a perfect candidate to replace fuse-umfuse-fat, then :) Do you intend on tagging a 0.2 release at some point or should I import from git?

**Comment by nabijaczleweli** [comment]
FTR, for now I've imported the HEAD from git (https://salsa.debian.org/salvage-team/fuse-umfuse-fat/-/blob/debian/0.2_22+c7f994d+dfsg-1/debian/watch?ref_type=tags), but it'd still be nice to have tags to pick up releases automatically.

**Comment by nabijaczleweli** [comment]
I can actually import git commits automatically too, so it's fine: https://salsa.debian.org/salvage-team/fuse-umfuse-fat/-/commit/9a242bc3ce5f65d30db7b5f9cdb9e0f911be5f94
